# Generated by Django 5.2.5 on 2025-08-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('payme', 'Payme'), ('click', 'Click'), ('atmos', 'Atmos')], max_length=10, null=True),
        ),
    ]
